# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Paul Fremantle

"""A turned profile read from a part someone actually made.

Every other piece of turned-step evidence in this repository is synthetic: one golden fixture
and a handful of stacked `Cylinder` calls. The two vendored corpora contribute nothing —
measured, all 50 NIST and MFCAD++ parts are milled prismatic and report **zero** turned steps.
So the family with the most tolerance-sensitive geometry had the least real geometry behind it,
and that is what let the defect below sit in a pinned fixture unnoticed.

Two parts from the author's own Gramel project, generated by build123d, both small enough that
the recogniser's absolute constants are comparable to their features — the ordinary case for a
turned part, not an edge case, and precisely where reading an OD by proximity rather than by
containment goes wrong.

``GRM-03`` is a 23.5 mm thumbwheel drive screw turned about **X**; ``GRM-05`` a 32 mm depth
lock bolt turned about **Z**; ``string_post`` a 14.8 mm instrument tuner post, also Z.

Two of the three had a rung misreported at 1:1 before the containment fix, which is the ratio
that matters: this is ordinary turned geometry, not a contrived case. GRM-05 passes on either
side of it and is kept for coverage — a 0.25 mm diameter change between two rungs, finer than
anything the synthetic fixtures contain.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from attribution_audit import attributed_run

pytest.importorskip("build123d")

from build123d import import_step  # noqa: E402

from quiddity import recognise_turned_steps  # noqa: E402
from quiddity._candidates import FamilyId  # noqa: E402
from quiddity._geometry import quantise  # noqa: E402
from quiddity.turned import _discover_turned_steps

CORPUS = Path(__file__).parent / "corpus" / "gramel"

#: Each part's rungs, as ``(diameter, lo, hi)``. Every rung must report the band that covers it.
#:
#: GRM-03's first rung is the one that used to be wrong: Ø6 runs from 0 to 0.5, and the Ø10 band
#: starting at 0.8 reached back over it on a 0.7 mm proximity pad.
EXPECTED = {
    "GRM-03_thumbwheel_drive_screw": [
        (6.0, 0.0, 0.5),
        (10.0, 0.5, 2.5),
        (5.0, 2.5, 5.5),
        (3.0, 5.5, 23.5),
    ],
    "GRM-05_depth_lock_bolt": [(10.0, 0.0, 14.0), (6.25, 14.0, 19.0), (6.0, 19.0, 32.0)],
    # The post's second rung is 1.1 mm wide at Ø5, and the Ø6 band butts against it at 8.3.
    # A 0.7 mm pad reached back to 7.6, past the rung's midpoint, and Ø6 outvoted the Ø5 the
    # rung sits inside.
    "string_post": [(3.4, 0.0, 7.2), (5.0, 7.2, 8.3), (6.0, 8.3, 13.8), (7.5, 13.8, 14.8)],
}


def _profile(part):
    """Significant figures, not decimals — for the reason this module exists.

    An earlier version rounded to three decimals and turned the Ø0.3125 rung of a bolt modelled
    at 0.05× into Ø0.312, failing the scale check by 0.16% for a defect in the check itself. A
    decimal quantum is a length, and a length has no business in a scale-free comparison.
    """

    return [
        (quantise(step.diameter), quantise(step.lo), quantise(step.hi))
        for step in sorted(recognise_turned_steps(part), key=lambda step: step.lo)
    ]


def test_split_widest_band_contributes_every_original_face() -> None:
    part = import_step(str(CORPUS / "string_post.step"))
    ledger, steps = attributed_run(
        part,
        FamilyId.TURNED_STEPS,
        recognise_turned_steps,
        discover=lambda led: _discover_turned_steps(part, ledger=led),
    )
    candidates = ledger.candidate_set(FamilyId.TURNED_STEPS).candidates

    assert len(steps) == len(candidates) == 4
    assert [len(ledger.defining_of(candidate)) for candidate in candidates] == [2, 1, 1, 1]
    for candidate, step in zip(candidates, steps, strict=True):
        defining_bounds = [ledger.graph.bounds(node) for node in ledger.defining_of(candidate)]
        axis = "xyz".index(step.axis)
        radial_span = max(
            max(bounds[index][1] for bounds in defining_bounds)
            - min(bounds[index][0] for bounds in defining_bounds)
            for index in range(3)
            if index != axis
        )
        assert round(radial_span, 3) == step.diameter


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_every_rung_reports_the_band_that_covers_it(name):
    """Each rung, at the size the part is actually made.

    Two of these three are regressions, and both failed at 1:1 rather than at any reduced
    scale — which is how the defect was first described and was wrong.

    GRM-03's first rung reported Ø10, the widest band on the screw, whose span starts at 0.8
    while the rung is 0 to 0.5: a 0.7 mm proximity pad bridged the 0.3 mm gap and outvoted the
    Ø6 the rung sits inside. ``string_post``'s second rung reported Ø6 where the band is Ø5,
    the same mechanism with the bands touching rather than gapped.

    Both recogniser versions also disagree with *themselves* across scales on those rungs —
    wrong at 1×, right at 5× and 100× — which is the signature of an absolute reach applied to
    a part whose features are the same order of size as it.

    GRM-05 passes on either side of the fix and is pinned for coverage.
    """

    assert _profile(import_step(str(CORPUS / f"{name}.step"))) == EXPECTED[name]


@pytest.mark.parametrize("name", sorted(EXPECTED))
@pytest.mark.parametrize("factor", (0.05, 5.0, 100.0))
def test_the_same_part_modelled_larger_has_the_same_profile(factor, name):
    """Scale-free as ratios, so no assertion depends on a length.

    0.05× was excluded when these fixtures arrived, for a different reason on each part: GRM-03
    gained a spurious shoulder that split a rung in two, and GRM-05's Ø6.25 band reported as
    Ø0.31 because the substrate quantised diameters to two decimals. Both are fixed, so all
    three parts are pinned at a twentieth scale — where a 14.8 mm post is 0.74 mm overall and
    every absolute constant in the recogniser is larger than the features it is judging.
    """

    rungs = EXPECTED[name]
    part = import_step(str(CORPUS / f"{name}.step"))
    widest = max(diameter for diameter, _, _ in rungs)
    span = max(hi for _, _, hi in rungs) - min(lo for _, lo, _ in rungs)
    expected = [
        (quantise(diameter / widest), quantise((hi - lo) / span)) for diameter, lo, hi in rungs
    ]

    scaled = _profile(part.scale(factor))
    widest_scaled = max(diameter for diameter, _, _ in scaled)
    span_scaled = max(hi for _, _, hi in scaled) - min(lo for _, lo, _ in scaled)
    actual = [
        (quantise(diameter / widest_scaled), quantise((hi - lo) / span_scaled))
        for diameter, lo, hi in scaled
    ]

    assert actual == expected
